### ISSUE TITLE
No module named 'neutrino.framework.profiler`

### ISSUE THREAD

**Issue by BhandarkarPawan** [Deeplite/neutrino#14]
I followed the steps in the Torch example for Deeplite-Profiler and I used the following line:
```
from neutrino.framework.profiler import Device, ComputeEvalMetric
```

But i get the error: 
```
ModuleNotFoundError: No module named 'neutrino.framework.profiler'
```

There's also no clear info about  `ComputeExecutionTime` and `ComputeComplexity`.
Where do I import it from?

**Comment by wernerchaodeeplite** [comment]
Some code snippet in the doc is outdated, and we will be updating within a week.
In the meantime, for code examples, please refer to: https://github.com/Deeplite/neutrino-examples

**Comment by wernerchaodeeplite** [comment]
@BhandarkarPawan if this resolves the problem I will be closing this issue. A new doc will be released today.

**Comment by wernerchaodeeplite** [comment]
Closing this as no response, I am assuming no more issue.

**Comment by BhandarkarPawan** [comment]
Sorry, I missed your message. This indeed solved my problem. Thanks
